export const USER_START='USER_START';
export const USER_SUCCESS='USER_SUCCESS';

export const USER_ERROR='USER_ERROR';


export const USER_CREATE_START='USER_CREATE_START';
export const USER_CREATE_SUCCESS='USER_CREATE_SUCCESS';

export const USER_CREATE_ERROR='USER_CREATE_ERROR';




export const USER_DELETE_START='USER_DELETE_START';
export const USER_DELETE_SUCCESS='USER_DELETE_SUCCESS';

export const USER_DELETE_ERROR='USER_DELETE_ERROR';




export const USER_UPDATE_START='USER_UPDATE_START';
export const USER_UPDATE_SUCCESS='USER_UPDATE_SUCCESS';

export const USER_UPDATE_ERROR='USER_UPDATE_ERROR';
